### ISSUE TITLE
As a volunteer, I want to get a walking list of addresses so that I know where to go.

### ISSUE THREAD

**Issue by joshsmith** [getmovement/movement-api#14]

**Comment by begedin** [comment]
PR #59 has added a very basic API for addresses. We should discuss everything we need here

# API Endpoints

## GET /addresses

Right now, the basic endpoint just lists all addresses. My guess is, we will be providing a location and a campaign ID when we figure out our system, and at that point, the endpoint will return a list of X nearest addresses applicable for that campaign. Or will addresses not be campaign specific at all and we just need to provide coordinates?

## POST /addresses

We had this in FieldTheBern, but will we have it here? How would it work in relation to our voter data?

## PATCH /addresses/:id

My guess is, we should have this one, so we can improve data accuracy. At the very least, we should be able to update coordinates. Anything else?

## GET /addresses:/id

We might want to get this endpoint to retrieve more details for an address (such as residents, past canvassing results, etc.). For this, we need to figure out our data structure.

# Data structure

## Fields

Address has the basic address fields (`:street_1`,`:street_2`,`:city`,`:state_code`,`:zip_code`,`:latitude`,`:longitude`) right now.

Will we be adding verification via USPS, for instance? At this point should that verification happen?

## Relationships

I'm not sure at all where to go wit this one. Some suggestions:
- `has_many :voters/:people`
- `has_many :canvass_results` (not sure how this table would look like)
- `has_many :visits`?

I'm just throwing things at the wall here to see what sticks. This is probably what we need to discuss the most.

# Policies

Fetching right now only requires the user to be authenticated and nothing else. My guess is, if we provide the campaign ID, the user should be a volunteer in that campaign in order to get a list of addresses? I can't think of anything else at the moment.

---

In any case, this is what I could think of right now. Any input is welcome here. Once we agree on what we need, we can create individual issues for those things.
